# Site settings
title: These Kids Read
email: thesekidsread@gmail.com
social: thesekidsread
description: We read great books together.
keywords: these kids read, jared pendergraft, kids books, great book for kids
baseurl: "" # /these-kids-read
url: "http://thesekidsread.com" # http://jaredpdesigns.github.io/these-kids-read
keep_files: [.git, "CNAME"]
exclude: ["README.md"]
source: src
destination: docs
host: 0.0.0.0

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css/pasta

# Outputting
permalink: /books/:categories/:title
paginate_path: /page:num

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  
# Autoprefixer
autoprefixer:
  browsers:
  - last 2 versions

plugins: [jekyll-autoprefixer, jekyll-sitemap]