# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: These Kids Read
email: thesekidsread@gmail.com
twitter: thesekidsread
description: My kids and I read great books together.
keywords: these kids read, jared pendergraft, kids books, great book for kids
baseurl: "" 
url: "http://thesekidsread.com" # the base hostname & protocol for your site
include: [".htaccess"]
exclude: ["gulpfile.js"]
keep_files: [".git"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css/_partials
  style: compressed

# Outputting
permalink: /books/:categories/:title
paginate_path: /page:num

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

gems:
- octopress-autoprefixer